name: Docker Build

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target: [backend, frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code Manually
        run: |
          # Configure git
          git config --global init.defaultBranch main
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          # Fetch only the necessary ref
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch --depth=1 origin +refs/pull/${{ github.event.pull_request.number }}/merge:refs/remotes/origin/pr
            git checkout -q origin/pr
          else
            git fetch --depth=1 origin ${{ github.sha }}
            git checkout -q ${{ github.sha }}
          fi

      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/${{ matrix.target }}"
          IMAGE="${IMAGE,,}" # Ensure lowercase
          
          # Build arguments
          TAGS="-t $IMAGE:${GITHUB_SHA::7} -t $IMAGE:latest"
          
          # Add version tag if on a tag
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAGS="$TAGS -t $IMAGE:${GITHUB_REF#refs/tags/v}"
          fi

          docker buildx build \
            $TAGS \
            --target prod \
            --cache-from=type=registry,ref=$IMAGE:cache \
            --cache-to=type=registry,ref=$IMAGE:cache,mode=max \
            --push ./${{ matrix.target }}
